# this docker will run a local redis instance
version: '3.5'

services:
  redis:
    image: redis:5
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379

  memcache:
    image: sameersbn/memcached:1.5.6-2
    ports:
      - 11211:11211
    restart: unless-stopped
